/*
 * This file is generated by jOOQ.
 */
package fr.javatic.noteapp.database.schema


import fr.javatic.noteapp.database.schema.tables.Note
import fr.javatic.noteapp.database.schema.tables.User
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.note</code>.
     */
    val NOTE: Note get() = Note.NOTE

    /**
     * The table <code>public.user</code>.
     */
    val USER: User get() = User.USER

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Note.NOTE,
        User.USER
    )
}
