/*
 * This file is generated by jOOQ.
 */
package fr.javatic.noteapp.database.schema.tables.references


import fr.javatic.noteapp.database.schema.tables.Note
import fr.javatic.noteapp.database.schema.tables.User


/**
 * The table <code>public.note</code>.
 */
val NOTE: Note = Note.NOTE

/**
 * The table <code>public.user</code>.
 */
val USER: User = User.USER
